### ISSUE TITLE
Alerts system doesn't hide itself anymore...

### ISSUE THREAD

**Issue by ryanmt** [princelab/metriculator#12]
@rjtman With the recent formatting changes, the alerts don't disappear when they are 'destroy'-ed.  I'm wondering if we should be using humane.js to handle those alerts as well... What do you think?

**Comment by russtaylor** [comment]
They're disappearing for me. Is this still an issue?

**Comment by ryanmt** [comment]
I can't test right now as they don't show up... I realized that I was seeing something different than the CSS dictated, due to the caching we'd discussed.
