### ISSUE TITLE
Can't figure out how to install for development.

### ISSUE THREAD

**Issue by jergason** [princelab/metriculator#3]
I am trying to set up a fresh copy of the app for development, and get stuck. Here is what I do:

```
$ git clone git@github.com:princelab/rails-metric_site.git && cd rails-metric_site
$ git checkout ryan #since this is the most recent branch I assume it is the dev one
#now set up my rvm gem environment
$ rvm gemset create archiver && rvm gemset use archiver
$ gem install bundler
$ bundle
#gems are not installed, so I'll try to run it
$ bundle exec rails s
=> Booting WEBrick
=> Rails 3.1.3 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/jergason/.rvm/gems/ruby-1.9.2-p290@archiver/gems/railties-3.1.3/lib/rails/application/configuration.rb:106:in `read': No such file or directory - /Users/jergason/dropbox/prince_lab_stuff/rails-metric_site/config/database.yml (Errno::ENOENT)
# then the big old stack trace
```

So there is no database.yml file. I guess I can just copy the default one over, but it looks like I have to edit the database.yml file so it points to where my databases will be. I change them to point to `/Users/jergason/Dropbox/prince_lab_stuff/rails-metric_site/db/rails_metric_site_[environment].db`, where `[environment]` is test, development, production, ect. Time to give it another go.

```
$ bundle exec rails s
```

Now the server starts, but I get:

```
DataObjects::ConnectionError in Pages#home

Showing /Users/jergason/dropbox/prince_lab_stuff/rails-metric_site/app/views/alerts/_alert_num.html.haml where line #2 raised:

unable to open database file.
```

Okay, looks like the database files are not created.

```
#see what install-related rake tasks exist
$ bundle exec rake -T
```

I see `rake db:automigrate`, which looks promising.

```
$ bundle exec rake db:automigrate
Cannot find or read /Users/jergason/dropbox/prince_lab_stuff/rails-metric_site/config/newrelic.yml
rake aborted!
unable to open database file

Tasks: TOP => db:automigrate
(See full trace by running task with --trace)
```

Running with --trace is not very helpful. I don't really know where to go from here. Have you tried installing from scratch recently? I am on a Mac, which hopefully shouldn't affect things, but might be a culprit.

**Comment by ryanmt** [comment]
I've installed from scratch in the last week.  I changed distros to LinuxMint.  

I use the `gem build archiver.gemspec` and `gem install archiver-0.0.1.gem` commands, and then proceed as you've described.   I modify the database.yml from the database example file included in the repo.  It hasn't given me the problems you are describing.  Any other pertinent details?  

I've pushed the newrelic.yml file, but you can also just silence that gem in the Gemfile, as you'll not likely need that particular tool right now...   Once that is done, hopefully the rake db:automigrate should work to build your databases.

**Comment by jergason** [comment]
I had my path to the db wrong. :(. At least this issue documents the install process a little now. I never would have guessed I needed to build and install the archiver gem without this. I'll have a go at adding this to the readme once I get it up and running.

**Comment by jergason** [comment]
Okay, seems to be working fine now. My issue really was with an error in the db path. :(
