### ISSUE TITLE
Adding comparisons to a comparison set produces multiple messages

### ISSUE THREAD

**Issue by jergason** [princelab/metriculator#4]
Not sure on steps to reproduce this one, as I have been unable to get a dev version of the app up and running. Could you give the steps that produce this bug Ryan?

**Comment by ryanmt** [comment]
Add any msrun to a potential comparison on the `msruns#show` page.  It flashes like 7 messages to me.

**Comment by jergason** [comment]
Yeah, I see the same thing. I have an idea of what it might be, so
hopefully a fix should be forthcoming.

On Fri, Dec 2, 2011 at 1:16 AM, Ryan Taylor
reply@reply.github.com
wrote:

**Comment by ryanmt** [comment]
You are going to be my hero.  I have NO idea what is causing it... I spent
some time trying to get some debugging done, but with the javascript buried
in the site, I wasn't very good at it.  Thanks.

Ryan

On Fri, Dec 2, 2011 at 11:31 AM, Jamison Dance <
reply@reply.github.com

**Comment by jergason** [comment]
Part of the problem is that some javascript files are being included twice. I have no idea how or where, but it may have to do with the assest pipeline stuff in Rails 3.1. I am not familiar with that at all, so I may have to dive down into that stuff.

**Comment by ryanmt** [comment]
It occurred before the shift to 3.1, as I recall.

On Fri, Dec 2, 2011 at 11:57 AM, Jamison Dance <
reply@reply.github.com

**Comment by jergason** [comment]
Well, I ended up just ripping out my crappy notification stuff and using humane.js. The styling for the notification thing is currently in `public/stylesheets/jackedup.css`, so that is where you would change how the notifications appear if you want a more consistent style. What do you think?
